version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "reddit-posts-gatherer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1r32z0l34n3hd"
s3_prefix = "reddit-posts-gatherer"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
